// game.qvm
cvar.register("gamename", "opensandbox", 0);
cvar.register("gamedate", new Date().toISOString().slice(0, 10), 0);
cvar.register("sv_cheats", "0", 0);
cvar.register("g_maxClients", "128", CVAR.SERVERINFO | CVAR.ARCHIVE);
cvar.register("g_maxEntities", "4096", CVAR.SERVERINFO | CVAR.ARCHIVE);
cvar.register("fraglimit", "20", CVAR.SERVERINFO | CVAR.ARCHIVE);
cvar.register("timelimit", "0", CVAR.SERVERINFO | CVAR.ARCHIVE);
cvar.register("capturelimit", "8", CVAR.SERVERINFO | CVAR.ARCHIVE);
cvar.register("g_gametype", "0", CVAR.SERVERINFO | CVAR.USERINFO | CVAR.LATCH);
cvar.register("g_entitypack", "default", CVAR.ARCHIVE);
cvar.register("g_jumpheight", "270", CVAR.SYSTEMINFO);
cvar.register("g_friendlyFire", "0", CVAR.ARCHIVE);
cvar.register("g_password", "", CVAR.USERINFO);
cvar.register("dedicated", "0", 0);
cvar.register("g_speed", "320", CVAR.ARCHIVE);
cvar.register("g_gravity", "800", CVAR.SYSTEMINFO);
cvar.register("g_knockback", "1000", 0);
cvar.register("com_blood", "1", 0);
cvar.register("g_enableDust", "0", CVAR.SERVERINFO);
cvar.register("g_enableBreath", "0", CVAR.SERVERINFO);
cvar.register("sv_fps", "60", CVAR.SYSTEMINFO | CVAR.ARCHIVE);
// cgame.qvm
cvar.register("headR", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("headG", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("headB", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("modelR", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("modelG", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("modelB", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("legsR", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("legsG", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("legsB", "100", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("physR", "128", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("physG", "225", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("physB", "255", CVAR.USERINFO | CVAR.ARCHIVE);
cvar.register("cg_effectsTime", "60", CVAR.ARCHIVE);
cvar.register("spawn_cmd", "0", 0);
cvar.register("toolgun_cmd", "0", 0);
cvar.register("toolgun_mod1", "0", 0);
cvar.register("toolgun_mod2", "0", 0);
cvar.register("toolgun_mod3", "0", 0);
cvar.register("toolgun_mod4", "0", 0);
cvar.register("toolgun_mod5", "0", 0);
cvar.register("toolgun_tool", "0", CVAR.USERINFO);
cvar.register("toolgun_tooltext", "", 0);
cvar.register("toolgun_tooltip1", "", 0);
cvar.register("toolgun_tooltip2", "", 0);
cvar.register("toolgun_tooltip3", "", 0);
cvar.register("toolgun_tooltip4", "", 0);
cvar.register("toolgun_toolmode1", "", 0);
cvar.register("toolgun_toolmode2", "", 0);
cvar.register("toolgun_toolmode3", "", 0);
cvar.register("toolgun_toolmode4", "", 0);
cvar.register("script.error", "0", 0);
cvar.register("cg_postprocess", "", 0);
cvar.register("cg_drawGun", "1", CVAR.ARCHIVE);
cvar.register("cg_zoomfov", "22", CVAR.ARCHIVE);
cvar.register("cg_fov", "110", CVAR.ARCHIVE);
cvar.register("cg_shadows", "1", CVAR.ARCHIVE);
cvar.register("cg_draw2D", "1", CVAR.ARCHIVE);
cvar.register("cg_drawTimer", "0", CVAR.ARCHIVE);
cvar.register("cg_drawFPS", "0", CVAR.ARCHIVE);
cvar.register("cg_drawSpeed", "0", CVAR.ARCHIVE);
cvar.register("cg_drawCrosshair", "4", CVAR.ARCHIVE);
cvar.register("cg_crosshairScale", "24", CVAR.ARCHIVE);
cvar.register("cg_addMarks", "1", CVAR.ARCHIVE);
cvar.register("cg_enableBobbing", "1", CVAR.ARCHIVE);
cvar.register("cg_thirdPersonRange", "65", CVAR.ARCHIVE);
cvar.register("cg_thirdPersonOffset", "25", CVAR.ARCHIVE);
cvar.register("cg_thirdPerson", "0", CVAR.ARCHIVE);
cvar.register("com_blood", "1", CVAR.ARCHIVE);
cvar.register("g_enableDust", "0", CVAR.SERVERINFO);
cvar.register("g_enableBreath", "0", CVAR.SERVERINFO);
cvar.register("cg_cameraEyes", "0", CVAR.ARCHIVE);
cvar.register("cg_cameraEyes_Fwd", "-2", CVAR.ARCHIVE);
cvar.register("cg_cameraEyes_Up", "7", CVAR.ARCHIVE);
cvar.register("sv_fps", "60", CVAR.SYSTEMINFO);
cvar.register("cg_crosshairColorRed", "0.5", CVAR.ARCHIVE | CVAR.USERINFO);
cvar.register("cg_crosshairColorGreen", "0.75", CVAR.ARCHIVE | CVAR.USERINFO);
cvar.register("cg_crosshairColorBlue", "1.0", CVAR.ARCHIVE | CVAR.USERINFO);
// ui.qvm
cvar.register("spawn_preset", "spawn_cmd = sl prop props/%s %s 0 25 25 0 %s 1 1 \"none\" -1 0 0 0 0 1 1 1 1 0.40 1.00", 0);
cvar.register("toolgun_toolset1", "--------:", 0);
cvar.register("toolgun_toolset2", "--------:", 0);
cvar.register("toolgun_toolset3", "--------:", 0);
cvar.register("toolgun_toolset4", "--------:", 0);
cvar.register("toolgun_tooltext", "", 0);
cvar.register("cl_selectedmod", "default", CVAR.ARCHIVE);
